In [35]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("fraud_data.csv")
df.shape[0]

In [36]:
from sklearn.model_selection import train_test_split

df = pd.read_csv('readonly/fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

    # Your code here
svm2 = SVC(C=1e9, gamma=1e-07).fit(X_train,y_train)
y_predict = svm2.predict(X_test)
conf_mat = confusion_matrix(y_test,y_predict)



In [ ]:

y_score_list1 = list(zip(y_test[0:200], y_scores_svm[0:200]))

In [37]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

lr = LogisticRegression().fit(X_train,y_train)
y_scores_lr = lr.fit(X_train, y_train).decision_function(X_test)

In [38]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_scores_lr)
plt.figure()
plt.xlim([0.0, 1.01])
plt.ylim([0.0, 1.01])
plt.plot(precision, recall, label='Precision-Recall Curve')


In [39]:
from sklearn.metrics import roc_curve, auc
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_scores_lr)

In [43]:
new = [round(x,2) for x in list(tpr_lr)]
new

[0.01,
 0.17999999999999999,
 0.17999999999999999,
 0.34000000000000002,
 0.34000000000000002,
 0.81000000000000005,
 0.81000000000000005,
 0.81999999999999995,
 0.81999999999999995,
 0.83999999999999997,
 0.83999999999999997,
 0.84999999999999998,
 0.84999999999999998,
 0.85999999999999999,
 0.85999999999999999,
 0.88,
 0.88,
 0.89000000000000001,
 0.89000000000000001,
 0.90000000000000002,
 0.90000000000000002,
 0.91000000000000003,
 0.91000000000000003,
 0.92000000000000004,
 0.92000000000000004,
 0.93999999999999995,
 0.93999999999999995,
 0.94999999999999996,
 0.94999999999999996,
 0.94999999999999996,
 0.94999999999999996,
 0.94999999999999996,
 0.94999999999999996,
 0.95999999999999996,
 0.95999999999999996,
 0.97999999999999998,
 0.97999999999999998,
 0.97999999999999998,
 0.97999999999999998,
 0.97999999999999998,
 0.97999999999999998,
 0.98999999999999999,
 0.98999999999999999,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [51]:
a = [0.234,0.678]

[round(x,2) for x in a]

[0.23, 0.68]

In [55]:
tpr_lr,fpr_lr

(array([ 0.0125,  0.175 ,  0.175 ,  0.3375,  0.3375,  0.8125,  0.8125,
         0.825 ,  0.825 ,  0.8375,  0.8375,  0.85  ,  0.85  ,  0.8625,
         0.8625,  0.875 ,  0.875 ,  0.8875,  0.8875,  0.9   ,  0.9   ,
         0.9125,  0.9125,  0.925 ,  0.925 ,  0.9375,  0.9375,  0.95  ,
         0.95  ,  0.95  ,  0.95  ,  0.95  ,  0.95  ,  0.9625,  0.9625,
         0.975 ,  0.975 ,  0.975 ,  0.975 ,  0.975 ,  0.975 ,  0.9875,
         0.9875,  1.    ,  1.    ,  1.    ,  1.    ,  1.    ,  1.    ]),
 array([  0.00000000e+00,   0.00000000e+00,   1.87125749e-04,
          1.87125749e-04,   3.74251497e-04,   3.74251497e-04,
          5.61377246e-04,   5.61377246e-04,   5.23952096e-03,
          5.23952096e-03,   1.47829341e-02,   1.47829341e-02,
          2.69461078e-02,   2.69461078e-02,   4.26646707e-02,
          4.26646707e-02,   6.17514970e-02,   6.17514970e-02,
          7.52245509e-02,   7.52245509e-02,   1.23315868e-01,
          1.23315868e-01,   1.37911677e-01,   1.37911677e-01,
     

In [56]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

    # Your code here
lr = LogisticRegression()

grid_values = {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}

    # default metric to optimize over grid parameters
grid_lr = GridSearchCV(lr, param_grid = grid_values, scoring = 'recall')
grid_lr.fit(X_train, y_train)
    
#     print(grid_lr.cv_results_['mean_test_score'].reshape(5,2))
ans = np.array(grid_lr.cv_results_['mean_test_score'].reshape(5,2))

In [57]:
grid_lr.cv_results_['mean_test_score']

array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
        0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.80797101])

In [58]:
ans

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.80797101]])

In [59]:
grid_lr.cv_results_

{'mean_fit_time': array([ 0.12463005,  0.32896558,  0.27502418,  0.321769  ,  0.33714636,
         0.41415254,  0.61551118,  0.46941797,  0.63919592,  0.46483787]),
 'mean_score_time': array([ 0.05364847,  0.16776999,  0.06079467,  0.02699018,  0.07650956,
         0.05518134,  0.08418345,  0.16378625,  0.15725295,  0.13668823]),
 'mean_test_score': array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
         0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.80797101]),
 'mean_train_score': array([ 0.68115942,  0.77355072,  0.80615942,  0.8134058 ,  0.81884058,
         0.81702899,  0.82427536,  0.82427536,  0.82427536,  0.82427536]),
 'param_C': masked_array(data = [0.01 0.01 0.1 0.1 1 1 10 10 100 100],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_penalty': masked_array(data = ['l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2'],
              mask = [False False False False False False Fals